name: poke_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.14
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logout.svg
    - assets/icons/refresh.svg
    - assets/icons/user.svg
